export const TASKS_LIST_REQUEST = "TASKS_LIST_REQUEST";
export const TASKS_LIST_SUCCESS = "TASKS_LIST_SUCCESS";
export const TASKS_LIST_FAIL = "TASKS_LIST_FAIL";

export const TASKS_CREATE_REQUEST = "TASKS_CREATE_REQUEST";
export const TASKS_CREATE_SUCCESS = "TASKS_CREATE_SUCCESS";
export const TASKS_CREATE_FAIL = "TASKS_CREATE_FAIL";

export const TASKS_UPDATE_REQUEST = "TASKS_UPDATE_REQUEST";
export const TASKS_UPDATE_SUCCESS = "TASKS_UPDATE_SUCCESS";
export const TASKS_UPDATE_FAIL = "TASKS_UPDATE_FAIL";

export const TASKS_DELETE_REQUEST = "TASKS_DELETE_REQUEST";
export const TASKS_DELETE_SUCCESS = "TASKS_DELETE_SUCCESS";
export const TASKS_DELETE_FAIL = "TASKS_DELETE_FAIL";
